### PR TITLE
Grid-272: Adding variable to handle editable column

### PR DESCRIPTION
**Pull request by glundgren93**
[Test Page](https://pp-datagridteam-dev.outsystemsenterprise.com/DataGridSample_DEV__272/Home.aspx)

Steps:

1.Go to datetime column.
2.Column should be non editable
3. Resize the column.
**Expected Result:** The value should not be cropped. For more context, check the video on the [JIRA issue.](https://outsystemsrd.atlassian.net/browse/GRID-272)

### CODE REVIEW

**Comment by glundgren93** [comment]
Updated the test page. My bad!

**Comment by tmbp95** [comment]
I believe it has been fixed

**Comment by tmbp95** [comment]
> I have to say I'm a bit concerned about using the Aria property to identify the readonly element.
> Is there a better way to uniquely identify this element?

Unless you change the class name or add a new one, I think this is the best approach without JS. Anyway, we can ask it to José Rosário 🤔

**Comment by glundgren93** [comment]
teste

**Pull request merged**
